name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Black + flake8
        run: pip install black flake8
      - name: Auto-fix with Black
        run: black .
      - name: Run flake8
        run: flake8 .

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pytest httpx python-dotenv
      - name: Run tests
        run: pytest -v

  security:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pip-audit bandit
      - run: pip-audit --desc
      - run: bandit -r . -s B101 #ignore the assert warning everywhere

  docker:
    needs: security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate semantic version
        id: version
        uses: paulhatch/semantic-version@v5.0.0
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING:"
          minor_pattern: "feat:"
          format: "${major}.${minor}.${patch}"

      # Docker Hub login
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Github Container Registry login
      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push both registries
      - name: Build and push to Docker Hub + GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            zakiayoubi/markviz:latest
            zakiayoubi/markviz:${{ steps.version.outputs.version }}
            gtcr.io/${{ github.repository }}:latest
            gtcr.io/${{ github.registrory }}:${{ steps.version.outputs.version }}