name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  # Job1: Test backend
  test-backend:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      API_NINJAS_KEY: ${{ secrets.API_NINJAS_KEY }}
      MASSIVE_API_KEY: ${{ secrets.MASSIVE_API_KEY }}

    steps:
      # Step 1: Get the code from Github
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: ./server
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      # Step 4: Run tests
      - name: Run tests
        working-directory: ./server
        run: pytest -v

  # Job 2: List Backend
  lint-backend:
    runs-on: ubuntu-latest
    needs: test-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Black
        run: pip install black==25.11.0

      # Check if code is formatted correctly
      - name: Check code formatting
        working-directory: ./server
        run: black --check app/

  # Job 3: Security Check
  security-check:
    runs-on: ubuntu-latest
    needs: test-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install bandit
        run: pip install bandit==1.8.0

      # Check for security concerns
      - name: Run security scan
        working-directory: ./server
        run: bandit -r app/ -ll # -ll only shows medium/high security issues

  # Job 4: Test frontend
  test-frontend:
    runs-on: ubuntu
    timeout-minutes: 2

    steps:
      - name: Check code
        uses: actions/checkout@v4

      - name: Set up Node.jobs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Build frontend
        working-directory: ./client
        run: npm run build