# name: Security

# on:
#   pull_request:
#     branches: [main]
#   push:
#     branches: [main]
#   schedule:
#     - cron: '0 3 * * *' # everyday at 3 am. 

# jobs:
#   security:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Install pip-audit
#         run: pip install pip-audit
#       - name: Install Scan for vulnerable packages
#         run: pip-audit